### ISSUE TITLE
Unique Midi Device Names

### ISSUE THREAD

**Issue by eh2k** [eh2k/squares-and-circles#67]
> I was thinking you maybe could give us the possibility to change the name for the input and output midi devices - that would be usefull too if we have more O-C/s connected.

> I would probably call mine "OC1 IN", "OC1 OUT", "OC2 IN", "OC2 OUT", "OC3 IN", "OC3 OUT", "OC4 IN", "OC4 OUT" and "OC4 IN", "OC4 OUT".

> Or do we have some other unique identifier going on that i'm not aware of ?

_Originally posted by @jpnielsen in https://github.com/eh2k/squares-and-circles/issues/66#issuecomment-1937049831_

**Comment by eh2k** [comment]
@jpnielsen 
I'm separating this as a separate issue - normally midi device names are hard coded in the code - but it might be possible that it can be done

**Comment by koswir** [comment]
Hey. @eh2k 
I really like the unique midi device names feature.
The problem is - the whole name is so long that software I use (Mi Rack) just cuts the number out.
Maybe we could shorten it to S&C #number?
![IMG_5561](https://github.com/eh2k/squares-and-circles/assets/151975047/86dbadce-361f-4fb5-811b-6825fff836c1)
I can see the whole name in some apps (eg AUM) but Mi Rack is what I use all the time and I always have to take a guess where midi goes 😉 
![IMG_5560](https://github.com/eh2k/squares-and-circles/assets/151975047/5603c765-5dbd-49a0-ab14-8039466079fd)

**Comment by eh2k** [comment]
Hi @koswir,

In the latest version (a819855), "S&C number" should already be displayed. Could it be that you are using an older S&C version?
You should also see the names here: https://studiocode.dev/webmidi-tester/

**Comment by koswir** [comment]
> Hi @koswir,
> 
> In the latest version ([a819855](https://github.com/eh2k/squares-and-circles/commit/a8198554224e1b85906e84ffecd1b0008560a2c4)), "S&C number" should already be displayed. Could it be that you are using an older S&C version? You should also see the names here: https://studiocode.dev/webmidi-tester/

yes I use the latest a819855 on all my o_cs.
I use them with an ipad, but I've checked on mac with the link you have provided and they are both called Squares&Circles.
